### ISSUE TITLE
FT230X Support

### ISSUE THREAD

**Issue by coliniuliano** [lorf/csr-spi-ftdi#29]
Hi,

FT230X support appears to be commented out from the source code.  Is there a reason?  With the FT233R chips broken bit bang modes, FT230X seems like a really good replacement.

Thanks

**Comment by lorf** [comment]
It was commented out because it was not available in the libftdi version I used at the moment I added it. Seems to be simple to make it a conditional at compile time. I'll look into it.

**Comment by lorf** [comment]
Enabled FT230X support in devel branch. Precompiled binaries for testing: https://github.com/lorf/csr-spi-ftdi/releases/tag/0.5.3-a1

**Comment by lorf** [comment]
Updated to mention whole FT-X family of chips, You will need to set `hwspi` pinout (https://github.com/lorf/csr-spi-ftdi/blob/master/README.md#options) to use FT230X. Precompiled binaries: https://github.com/lorf/csr-spi-ftdi/releases/tag/0.5.3-a4

**Comment by lorf** [comment]
I thought it would be easy ;) Will check FT230X docs...

Overflow is fixed in devel branch, thanks!

**Comment by lorf** [comment]
There is some changes WRT FT230X in libftdi-1.4, can You please, try the binaries compiled with this version of liibftdi: https://github.com/lorf/csr-spi-ftdi/releases/tag/0.5.3-a5

**Comment by coliniuliano** [comment]
Hi,

The new version appears to work well, thank you!  I realize now that the reason my chip did not initially identify is because I was using nvscmd.exe from the CSR64xxx tools instead of from BlueModify.  I'm still unable to get the firmware working, but I can confirm that the FT230X support works!

Thanks!
